package lexico;

public enum Categoria {

	NUMERO_NATURAL, 
	NUMERO_REAL, 
	IDENTIFICADOR, 
	PALABRA_RESERVADA, 
	OPERADOR_ARITMETICO, 
	OPERADOR_RELACIONAL, 
	OPERADOR_LOGICO,
	OPERADOR_ASIGNACION, 
	OPERADOR_INCREMENTO_DECREMENTO,
	PARENTESIS,
	LLAVES,
	TERMINAL,
	SEPARADOR,
	HEXADECIMAL,
	CADENA_CARACTERES,
	COMENTARIO,
	DESCONOCIDO 

}
